

#CROSS_COMPILE ?= arm-linux-


all:
	$(CROSS_COMPILE)g++ main.c -o test -static -g
	$(CROSS_COMPILE)g++ main2.c -o test2 -static -g
	$(CROSS_COMPILE)g++ main3.c -o test3 -static -g



clean:
	rm *.o test



